### ISSUE TITLE
no reconnection if Bluetooth has been turned off

### ISSUE THREAD

**Issue by storma** [smokku/pebble#43] opened 2015-03-07 05:08 UTC
I've set up situations to turn off Bluetooth and enable the general profile when I'm at home as i take off my pebble. When I leave again, it reverts to a pebble profile and turns Bluetooth back on. Problem is that the pebble will only reconnect after I tap "connection" from within the app.

If I lose Bluetooth connection, drops out from leaving phone behind, it will reconnect automatically when within distance again.

**Comment by raketti** [comment] 2015-04-21 07:53
I have the same issue and I think it's a bit annoying. Otherwise the Pebble app works great. I don't know if the Pebble searches for nearby phones or if the connection is always initialised from the Phone. If the connection is woked by the pebbled daemon, then it should automagically poll for the paired watches.

There's an option to run a specific command when a situation is turned on, but I couldn't find how to initialise the pairing between the app and the watch. If I run pebble or pebbled it will only start another instance of the daemon/app. So if someone could provide (I'm not that tech'y to go through logs and code) a command to connect to the Pebble, that would be a good workaround. To clarify, I'm talking about the command run when the cover app is flicked to connect to the Pebble.

**Comment by smurfy** [comment] 2015-04-21 07:57
I'm not 100% sure, i did not look at the code if this changed, but i think the reconnect timer has no upper limit (the time the phone tries to reconnect increases)
I wanted to check this a while back but i did not have the time.

So maybe this is the problem?

**Comment by abranson** [comment] 2015-04-21 08:59
I don't think it's that, here's the current logic (I think):

    if (reconnectTimer.interval() < 10 * RECONNECT_TIMEOUT) {
        reconnectTimer.setInterval(reconnectTimer.interval() + RECONNECT_TIMEOUT);
    }

RECONNECT_TIMEOUT is defined as 500, so it should max out at 5 secs, no?

**Comment by smokku** [comment] 2015-04-21 09:44
I was already debugging this issue ant the problem is that once the BT has been turned off and on, the daemon sees the device around, but is unable to establish the serial connection.
I have no idea why.

**Comment by abranson** [comment] 2015-04-21 10:45
I had a go at this, and it seems to work. Sometimes I get a couple of QBluetoothSocket::UnknownSocketError "Resource temporarily unavailable" when it's turned back on, but that seems to be due to the local bt not being properly initialized yet, and it eventually connects. It seems to get stuck if you try to connect while it's off though, so i added a check for that. Does that sound in line with your debugging?

**Comment by smokku** [comment] 2015-04-21 11:22
Could be. I didn't attempt to suppress reconnection when BT is off.

**Comment by abranson** [comment] 2015-04-29 19:59
This should be fixed by my last PR

**Comment by smokku** [comment] 2015-04-30 14:37
Please test whether https://github.com/smokku/pebble/releases/tag/3f64297 pre-release solves this issue.

**Comment by storma** [comment] 2015-05-01 07:13
Initial testing went well for my use cases. Haven't tested over an extended period of time yet.

Greatly appreciated, thanks!

**Comment by smokku** [comment] 2015-05-01 09:04
Closing then.
Feel free to reopen if anything happens.

**Closed by smokku** 2015-05-01 09:04 UTC
