### ISSUE TITLE
Lost call notification / broken connection in deep sleep

### ISSUE THREAD

**Issue by Fuzzillogic** [smokku/pebble#33] opened 2015-01-19 18:07 UTC
On a few occasions my Pebble didn't notify me of an incoming call, although the Pebble claimed it was connected. I did notice the message "Pebble connected" (bluetooth) after the call was ended, as if really wasn't connected before. The phone was (probably) in deep sleep when it received the calls; I had no internet-connected apps are running, and the phone was on battery.

Probably related, I noticed a broken connection due to out-of-range isn't re-established automatically when the phone is in deep sleep. As soon as I wake the phone, even if only triggering the proximity sensor (I've LPS enabled), the Pebble reconnects.

STR:
* Connect Pebble.
* Leave the phone be for a while, so it enters power save mode; I've WLAN disabled, if that matters.
* Walk out of range; Pebble disconnects.
* Wait a bit.
* Walk back in range. Notice that connection remains broken.
* Wake phone, by tapping/power button/proximity sensor.
* Pebble reconnects.

However, I've had no issues receiving notifications of e-mail. It might be that the device is active a bit longer (busy fetching the mail etc) before actually generating the notification, allowing the BT-connection to re-establish.

Perhaps [this thread on the mailinglist](https://lists.sailfishos.org/pipermail/devel/2014-February/003261.html) might be of help?

**Comment by smokku** [comment] 2015-01-19 18:59
I can confirm the issue of phone call during the deep sleep. I noticed that and tried to work around it by re-sending last message if a connection down is detected while sending message to watch. I guess it didn't work. :(

The second issue reported here is a bit different. Is there a reason to reconnect if the device is in power save mode and has nothing to send to the phone? Just for the sake of nice bluetooth icon on the watch? We can wake the phone every few seconds just to reestablish BT connection, but is it worth the battery life?

P.S. For future, please report two issues in two separate github issues. It's difficult to maintain two threads of conversation in one github issue.

**Comment by Fuzzillogic** [comment] 2015-01-19 19:24
But yeah, there are plenty reasons why it's important to verify the connection is still functional. If the indication is not reliable, you wouldn't know whether the battery has ran out, or you really still are out-of-range, or whether your phone is still in silent mode - you might be out-of-BT-range, but within hearing range *if* the phone had automatically reverted to sound because of the severed connection.

FWIW, I'm currently using my phone as USB modem, so it probably won't enter sleep mode. It quickly and accurately responds to going out / coming in range, so I reckoned it is same or related to the same deep sleep issue.

**Comment by Fuzzillogic** [comment] 2015-01-21 19:26
I've noticed that apps can't connect to the device when the connection has been lost while the phone was in sleep mode. E.g. a weather app can't get updates anymore. You have to actively wake the phone so it can reconnect.
The app [Kitchen Timer](https://github.com/tanghus/kitchen-timer-qml) uses Nemo's libiphb which allows for wake-ups even in sleep mode. Those wake-ups are synchronized with other events, which make it more battery friendly. Might be useful here.

**Comment by eras** [comment] 2015-02-23 13:32
This issue seems to have hit me three times today: I do get a notification of the missed call, though. Perhaps some workarounds could be tried?

I imagine my phone was in deep sleep in my pocket these times, but I cannot really confirm that.. I have received phone call notifications earlier on my Pebble. I do have "Forward calls" enabled. I also had disabled forwarding for "Mitakuuluu"; just mentioning this in case there could be a related bug.

I am fairly certain I have not disconnected the phone connection, because I have the Bluetooth disconnected -alarm on my Pebble.

Related to Wlan: I haven't connected to WiFi at work where it didn't work, I may have been connected to WiFi at home where it worked (but it's not certain).

Fortunately I didn't recognize any of the number even with a phone book search, so they were probably telemarketers ;-).

**Comment by nikhau** [comment] 2015-03-04 19:51
"On a few occasions my Pebble didn't notify me of an incoming call, although the Pebble claimed it was connected. I did notice the message "Pebble connected" (bluetooth) after the call was ended, as if really wasn't connected before."

This exact thing has happened to me too a couple of times the last week.

Pebble FW 2.9
Sailfish 1.1.2.16

**Comment by eras** [comment] 2015-03-13 10:53
Just now I had a case where the phone definitely wasn't in deep sleep (I was reading a web page), a call arrived, but no notification on Pebble. However, after I had ignored the call, the notification of the missed call did arrive. So this may not be related to deep sleep after all, or at least not all cases?

Shortly before this had happened I did receive "Pebble disconnected" "Pebble connected" messages, but the Pebble watch face did not vibrate in between to indicate a disconnection. Maybe this is related, maybe not.

Pebble firmware 2.9, Sailfish 1.1.2.16.

**Comment by nikhau** [comment] 2015-04-22 14:13
I just had a case, phone on desk only 30 cm from my Pebble. Incomming call and no notification on my Pebble. The phone was used max 10 min before this. After I ended the call, I checked and the app stated that a connection to pebble is present.

Pebble FW 2.9.1
Sailfish 1.1.4.28
Pebbled 1.0-1

**Comment by nikhau** [comment] 2015-05-13 14:43
Updated to 1.1 and the problem continues, now I would say even more. Also sms notifications are not transferred to the Pebble watch, Don't know if related or not.

Pebble FW 2.9.1
Sailfish 1.1.4.29
Pebbled 1.1

**Comment by smokku** [comment] 2015-06-19 08:26
Most probably fixed with #71 in release 1.3.
If not, do not hesitate to reopen.

**Closed by smokku** 2015-06-19 08:26 UTC
